### ISSUE TITLE
Kodi stürzt nach video Auswahl ab / Kodi crashes after Starting playback

### ISSUE THREAD

**Issue by Martin1995** [MrKrabat/plugin.video.akibapass#2]
2017-12-18
Seit gestern stürzt mein Kodi17.6 (Arch Linux x86_64, rolling release, LTS-Kernel) ab sobald ich versuche über das akibapass Addon eine Episode zu streamen. Angemeldet bin ich mit nem account der ein 30 tage Probe Abo hat und am 16. Dezember 2017 funktionierte das einwandfrei, ich konnte vier Episoden nacheinander schauen ohne Probleme.

Ich hätte gerne ein wenig unterstützung was die Fehlersuche angeht, da ich nicht weis ob das System Bedingt oder Addon bedingt ist.

Zu betonen wäre noch dass ich ein Notebook verwende das Optimus von nVidia verbaut habe und die Dedizierte Grafikkarte (Kein Anschluss für monitor) zum Rendern und die Intel Grafikkarte (HDMI VGA und LVDS) für die Ausgabe nutze.

Ein weiterer Punkt ist dass das Video ja geladen wird und danach beim versuch dieses Wiederzugeben dann das Mediacenter Abstürzt.

MfG
Martin
ps: ich werde auch noch in meine Logfiles schauen ob ich was finde und das dann anhängen

**Comment by MrKrabat** [comment]
Hallo,
bei mir funktioniert das Addon noch ohne Probleme.

Ein Debug Log könnte helfen aber ich vermute stark, dass das Problem an deinem System oder Kodi selbst liegt.

Grüße,
MrKrabat

**Comment by Martin1995** [comment]
Heute mal wieder das addon getestet und ich weis nicht was das Problem war aber es scheint wieder einwandfrei zu funktinoieren. es könnte auch eine systembedingte sache sein weil vier tage vorher ging an meinem gerät die dedizierte grafik nicht mehr nur noch die onboard intel (treiberprobleme) könnte sein dass es davon kam und einige abhängigkeiten in verbindung mit dem addon den absturz verursacht haben.

**Comment by MrKrabat** [comment]
das ist schön zu hören, dass es wieder geht :)
